### PR TITLE
upgraded redux to 1.0.0-alpha

### PR DESCRIPTION
**Pull request by keyz**
Also added `Immutable.js`, and a dummy handler for data fetching errors. 

This probably should be merged to a new `redux@1.0.0-alpha` upstream branch since the API may change again. Thanks for reviewing! cc @gaearon

### CODE REVIEW

**Comment by emmenko** [comment]
@keyanzhang wow, thanks! LGTM :+1: 

Should we wait for a stable `1.0` API before merging it?

**Comment by keyanzhang** [comment]
@emmenko We use `redux` to develop a real-time app in production and we are closely watching the API changes. In other words, if we set up an `redux@1.0.0` branch I can keep updating it :grinning:

**Comment by emmenko** [comment]
@keyanzhang here we go `redux-1.0`.

Thanks again for your contribution!

**Comment by keyz** [comment]
My pleasure!

**Pull request closed without merging**
