### PR TITLE
Fix for binding props and context

### PR DESCRIPTION
**Pull request by vincent-dm**

### CODE REVIEW

**Comment by emmenko** [comment]
Thanks but the binding is [already done](https://github.com/vincent-dm/redux-react-router-async-example/blob/router-login/lib/components/pages/Login.js#L37) by `::`. 

See https://github.com/zenparsing/es-function-bind

Is it not working?

**Comment by vincent-dm** [comment]
My bad... I removed the :: when adopting your code to my ESLint standards, as it was marked as an error. Wasn't aware that I caused the problem this way.

Any reason why you don't use the connect() method to bind store and router when initializing the Application component? (as in the Redux todo-example).

Thanks for the great skeleton project by the way!

**Comment by emmenko** [comment]
Ok :)

> Thanks for the great skeleton project by the way!

Glad it helps! ;)

> Any reason why you don't use the connect() method to bind store and router when initializing the Application component

Hmm, not sure I understand what you mean...

**Comment by vincent-dm** [comment]
I'm very new to Redux/React, so it is probably something I'm missing. But I am trying to reconcile the differences between your app and the examples on the Redux 1.0 documentation.

In your Login component the store and router are part of this.context.

In the Redux todo-example, they are bound to this.props. (See containers/App.js at http://gaearon.github.io/redux/docs/basics/ExampleTodoList.html)

**Comment by vincent-dm** [comment]
Also, any reason why you use a constructor to bind this in lib/components/github/Explore.js and not the :: syntax?

I understand that this branch is not really published and it's logical that there are inconsistencies. But as a beginner it is hard to see which variations are due to "work in progress" and which ones have an underlying reason...

**Comment by emmenko** [comment]
Good points, will try to answer them tonight (currently quite busy with work) :)

Thanks!

**Comment by vincent-dm** [comment]
great; looking forward to it!

**Comment by emmenko** [comment]
> In your Login component the store and router are part of this.context.

Well, since I have to transition I need the `router`, which can only be accessed via context. About the `store` I access it also via context because it's much easier to get the `dispatch` method. Otherwise I would have to `connect` the `Login` component and get `dispatch` as a prop, but in the login case it's not really necessary (at least as it is now). 
This might also change with the [new upcoming API](https://github.com/gaearon/react-redux/pull/16) for `connect`.

In general, try to avoid using `context` if it's not really necessary.

> Also, any reason why you use a constructor to bind this in lib/components/github/Explore.js and not the :: syntax?

You're right, it's not consistent.

> But as a beginner it is hard to see which variations are due to "work in progress" and which ones have an underlying reason...

I know, I actually wanted to merge the login branch (need some more cleanup) and add JSDoc or comments to explain some of the choices. Unfortunately I'm extremely busy with work atm, I hope to find some time soon.

Hope this answer your question, otherwise feel free to ask more :)

**Pull request closed without merging**
